In [1]:
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, Lasso, ElasticNet, Ridge

In [2]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.linear_model import LinearRegression, ElasticNet, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor,AdaBoostClassifier, AdaBoostRegressor, BaggingRegressor, BaggingClassifier
from sklearn.svm import SVR, SVC
import xgboost as kg

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_squared_error, f1_score

In [4]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

In [5]:
from sklearn.metrics import confusion_matrix

In [6]:
cases = pd.read_csv('ody.csv')

In [7]:
cases.head()

cl  hom  gun  rape  sex  robb  burg  driv  \
0  {'Misdemeanor B', 'Misdemeanor C'}    0    0     0    0     0     0     1   
1                   {'Misdemeanor A'}    0    0     0    0     0     0     0   
2                        {'Felony A'}    0    0     0    0     0     0     0   
3                   {'Misdemeanor C'}    0    0     0    0     0     0     0   
4                   {'Misdemeanor A'}    0    0     0    0     0     0     0   

                           ch                 name  ...             retained  \
0  {'55-50-504', '55-12-139'}      BANKS, MORGAN S  ...                  NaN   
1               {'39-17-418'}  BLACK, DAJAVANTAY J  ...     Harris, Jayniece   
2               {'39-17-434'}       BASS, GARRISON  ...             Retained   
3  {'39-17-310', '39-14-405'}        HALL, JAMES E  ...                  NaN   
4               {'39-13-111'}        CROCKER, CHAD  ...  BRASHIER, KENNETH W   

    case_no                   judge        date  \
0  21000002  Montesi, Louis J., Jr.  01/01/2021   
1  21000003  Anderson, William Bill  01/01/2021   
2  21000004              Dwyer, Tim  01/01/2021   
3  21000005  Montesi, Louis J., Jr.  01/01/2021   
4  21000008      Turner, William C.  01/01/2021   

                                   type         status bond_amt  \
0                    Misdemeanor Arrest       Disposed      0.0   
1                    Misdemeanor Arrest       Disposed    250.0   
2                    Felony Arrest Drug  Held to State   3500.0   
3                    Misdemeanor Arrest       Disposed      0.0   
4  Misdemeanor Arrest Domestic Violence       Disposed   1500.0   

     bond_status  era  log_bond  
0         Posted  0.0  0.000000  
1  Case Disposed  0.0  5.525453  
2  Held To State  0.0  8.160804  
3         Posted  0.0  0.000000  
4  Case Disposed  0.0  7.313887  

[5 rows x 24 columns]

In [8]:
cases['ror'] = cases['bond_amt'].apply(lambda x: 1 if x == 0 else 0)

In [10]:
cases.isnull().sum().head(50)

cl                0
hom               0
gun               0
rape              0
sex               0
robb              0
burg              0
driv              0
ch                0
name              0
dob              25
race              0
zip            5858
atty           2858
retained       2858
case_no           0
judge             0
date              0
type              0
status          282
bond_amt          0
bond_status       0
era               0
log_bond          0
ror               0
dtype: int64

In [45]:
X = cases[['ch','race']]

In [46]:
y = cases['ror']

In [47]:
ohe = OneHotEncoder()
X = ohe.fit_transform(X).toarray()

In [48]:
X = pd.DataFrame(X, columns=ohe.get_feature_names_out())

In [49]:
X_train,X_test,y_train,y_test = train_test_split(X, y, stratify=y, random_state=42)

In [50]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((4887, 1301), (1629, 1301), (4887,), (1629,))

In [51]:
base = [0]*len(y_test)

In [52]:
confusion_matrix(y_test,base)

array([[899,   0],
       [730,   0]], dtype=int64)

In [53]:
logr = LogisticRegression(C=1000)
logr.fit(X_train,y_train)
confusion_matrix(y_test,logr.predict(X_test))

C:\Anaconda\envs\tfm1\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([[731, 168],
       [575, 155]], dtype=int64)

In [54]:
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train,y_train)
confusion_matrix(y_test,knn.predict(X_test))

array([[619, 280],
       [500, 230]], dtype=int64)

In [55]:
gnb = GaussianNB()
gnb.fit(X_train,y_train)
confusion_matrix(y_test,gnb.predict(X_test))

array([[ 39, 860],
       [ 35, 695]], dtype=int64)

In [56]:
mnb = MultinomialNB()
mnb.fit(X_train,y_train)
confusion_matrix(y_test,mnb.predict(X_test))

array([[811,  88],
       [647,  83]], dtype=int64)

In [57]:
bnb = BernoulliNB()
bnb.fit(X_train,y_train)
confusion_matrix(y_test,bnb.predict(X_test))

array([[813,  86],
       [646,  84]], dtype=int64)

In [58]:
dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)
confusion_matrix(y_test,dt.predict(X_test))

array([[710, 189],
       [583, 147]], dtype=int64)

In [220]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
confusion_matrix(y_test,rf.predict(X_test))

array([[836,  63],
       [678,  52]], dtype=int64)

In [275]:
from sklearn.svm import SVC

In [ ]:
svc = SVC(kernel = 'linear')
svc.fit(X_train,y_train)
confusion_matrix(y_test,svc.predict(X_test))

In [ ]:
abc = AdaBoostClassifier(n_estimators = 50)
abc.fit(X_train,y_train)
confusion_matrix(y_test,abc.predict(X_test))

In [88]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.metrics import Recall, Precision

In [107]:
model = Sequential()
model.add(Dense(32,activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics = [Precision()])

In [108]:
model.fit(X_train,y_train,validation_data=(X_test, y_test), epochs = 50, batch_size = 36)

Epoch 1/50
136/136 [==============================] - 2s 5ms/step - loss: 0.6899 - precision: 0.4469 - val_loss: 0.6879 - val_precision: 0.0000e+00
Epoch 2/50
136/136 [==============================] - 0s 2ms/step - loss: 0.6848 - precision: 0.6000 - val_loss: 0.6886 - val_precision: 0.5484
Epoch 3/50
136/136 [==============================] - 0s 3ms/step - loss: 0.6764 - precision: 0.6176 - val_loss: 0.6924 - val_precision: 0.4519
Epoch 4/50
136/136 [==============================] - 0s 3ms/step - loss: 0.6547 - precision: 0.6211 - val_loss: 0.7057 - val_precision: 0.4457
Epoch 5/50
136/136 [==============================] - 0s 3ms/step - loss: 0.6249 - precision: 0.6288 - val_loss: 0.7206 - val_precision: 0.4506
Epoch 6/50
136/136 [==============================] - 0s 3ms/step - loss: 0.5935 - precision: 0.6385 - val_loss: 0.7430 - val_precision: 0.4495
Epoch 7/50
136/136 [==============================] - 0s 3ms/step - loss: 0.5789 - precision: 0.6302 - val_loss: 0.7638 - val_precis

In [109]:
model.evaluate(X_test,y_test)

51/51 [==============================] - 0s 1ms/step - loss: 0.9247 - precision: 0.4432


[0.9246808886528015, 0.4432132840156555]

In [110]:
y_pred = model.predict(X_test) > 0.45

51/51 [==============================] - 0s 1ms/step


In [111]:
confusion_matrix(y_test,y_pred)

array([[314, 585],
       [244, 486]], dtype=int64)